### ISSUE TITLE
`mason login` on Amazon Linux: "TypeError: request() got an unexpected keyword argument 'json'"

### ISSUE THREAD

**Issue by rjhacks** [MasonAmerica/mason-cli#3]
Running `mason login` on my Mac OS machine works fine. However, on Amazon Linux, it crashes:

> $ mason login
> User: [...]
> Password: [...] 
> Traceback (most recent call last):
>   File "/usr/local/bin/mason", line 11, in <module>
>     load_entry_point('mason-cli==0.95', 'console_scripts', 'mason')()
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib64/python2.7/site-packages/click/decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/local/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/mason.py", line 297, in login
>     if not config.mason.authenticate(user, password):
>   File "/usr/local/lib/python2.7/site-packages/masonlib/internal/mason.py", line 396, in authenticate
>     r = requests.post(self.store.auth_url(), json=payload)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
>     return request('post', url, data=data, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
> TypeError: request() got an unexpected keyword argument 'json'

The password I type doesn't matter.

Here's the output of `mason version`:

> $ mason version
> mason (Mason America) 0.95
> Copyright (C) 2018 Mason America
> License Apache 2.0 <https://www.apache.org/licenses/LICENSE-2.0>

I use an Amazon Linux box as my primary dev environment, so I'd appreciate having this fixed!

**Comment by scorpiodawg** [comment]
Thanks for the report!

Is this specifically on Amazon Linux? We've tested on Ubuntu 14 and 16 and have not seen this. I suspect it has to do with the default Python installation on these OSs not having an up to date version of `requests`.

Are you able to get around this by installing `mason-cli` inside a `virtualenv`?

**Comment by SUPERCILEX** [comment]
Closing as obsolete. If it still doesn't work with the [latest release](https://docs.bymason.com/mason-cli/#install), please open a new bug.
